apiVersion: batch/v1
kind: CronJob
metadata:
  name: qiniu-cert-sync
  namespace: yournamespace
spec:
  jobTemplate:
    metadata:
      name: qiniu-cert-sync
    spec:
      template:
        spec:
          containers:
          - image: bohrasd/qiniu-cert-sync
            name: qiniu-cert-sync
            command: [ "/bin/qiniu-cert-sync" ]
            resources: {}
            volumeMounts:
              - name: config-volume
                mountPath: /etc/qiniu-cert-sync
          volumes:
            - name: config-volume
              configMap:
                name: qiniu-cert-sync-config
          restartPolicy: OnFailure
          serviceAccount: qiniu-cert-sync
          serviceAccountName: qiniu-cert-sync
  schedule: 0 1 * * 1

---
apiVersion: v1
data:
  config.toml: |
    mode = "cluster"

    [qn_auth]
    qiniu_access_key = ""
    qiniu_secret_key = ""

    [[secrets]]
    secret = "wildcard-example-tls-secret"
    namespace = "example"
    common_name = ["abc.example.com", "def.example.com"]

    [[secrets]]
    secret = ""
    namespace = ""
    common_name = []
kind: ConfigMap
metadata:
  name: qiniu-cert-sync-config
  namespace: yournamespace

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-watch
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qiniu-cert-sync
  namespace: yournamespace

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: qiniu-cert-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-watch
subjects:
- kind: ServiceAccount
  name: qiniu-cert-sync
  namespace: yournamespace
